FROM ubuntu:latest

RUN apt update && \
    apt install -y openssh-server

RUN mkdir /run/sshd -p && \
    chmod 0755 /run/sshd && \
    chown root:root /run/sshd && \
    echo 'root:root' | chpasswd

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-f", "/tmp/ssh/config"]